items:
  iron_core:
    customModelID: 1
  gold_core:
    customModelID: 1
  diamond_core:
    customModelID: 1
  emerald_core:
    customModelID: 1
  magnetised_iron:
    customModelID: 1
  copper_ingot:
    customModelID: 1
  wrench:
    customModelID: 61
  configurator:
    customModelID: 62
  steel_ingot:
    customModelID: 1
  iron_dust:
    customModelID: 1
  gold_dust:
    customModelID: 1
  diamond_dust:
    customModelID: 1
  emerald_dust:
    customModelID: 1
  copper_dust:
    customModelID: 1
  coal_dust:
    customModelID: 1

  light_off:
    customModelID: 63
  light_on:
    customModelID: 65
  invisible:
    customModelID: 5
  output:
    customModelID: 6
  output_disabled:
    customModelID: 7
  output_green:
    customModelID: 8
  output_disabled_alt:
    customModelID: 67
  output_green_alt:
    customModelID: 68
  bar_0_b:
    customModelID: 9
  bar_1_b:
    customModelID: 10
  bar_2_b:
    customModelID: 11
  bar_3_b:
    customModelID: 12
  bar_4_b:
    customModelID: 13
  bar_5_b:
    customModelID: 14
  bar_6_b:
    customModelID: 15
  bar_7_b:
    customModelID: 16
  bar_8_b:
    customModelID: 17
  bar_9_b:
    customModelID: 18
  bar_10_b:
    customModelID: 19
  bar_11_b:
    customModelID: 20
  bar_12_b:
    customModelID: 21
  bar_13_b:
    customModelID: 22
  bar_14_b:
    customModelID: 23
  bar_15_b:
    customModelID: 24
  bar_16_b:
    customModelID: 25
  bar_17_b:
    customModelID: 26
  bar_18_b:
    customModelID: 27
  bar_19_b:
    customModelID: 28
  bar_20_b:
    customModelID: 29
  bar_0_t:
    customModelID: 30
  bar_1_t:
    customModelID: 31
  bar_2_t:
    customModelID: 32
  bar_3_t:
    customModelID: 33
  bar_4_t:
    customModelID: 34
  bar_5_t:
    customModelID: 35
  bar_6_t:
    customModelID: 36
  bar_7_t:
    customModelID: 37
  bar_8_t:
    customModelID: 38
  bar_9_t:
    customModelID: 39
  bar_10_t:
    customModelID: 40
  bar_11_t:
    customModelID: 41
  bar_12_t:
    customModelID: 42
  bar_13_t:
    customModelID: 43
  bar_14_t:
    customModelID: 44
  bar_15_t:
    customModelID: 45
  bar_16_t:
    customModelID: 46
  bar_17_t:
    customModelID: 47
  bar_18_t:
    customModelID: 48
  bar_19_t:
    customModelID: 49
  bar_20_t:
    customModelID: 50
  arrow_0:
    customModelID: 51
  arrow_1:
    customModelID: 52
  arrow_2:
    customModelID: 53
  arrow_3:
    customModelID: 54
  arrow_4:
    customModelID: 55
  arrow_5:
    customModelID: 56
  arrow_6:
    customModelID: 57
  arrow_7:
    customModelID: 58
  arrow_8:
    customModelID: 59
  arrow_9:
    customModelID: 60
  IronCell:
    customModelID: 1
  GoldCell:
    customModelID: 2
  DiamondCell:
    customModelID: 3
  EmeraldCell:
    customModelID: 4
  SolidFuelGenerator:
    customModelID: 13
  power_connector:
    customModelID: 14
  IronElectricFurnace:
    customModelID: 9
  GoldElectricFurnace:
    customModelID: 10
  DiamondElectricFurnace:
    customModelID: 11
  EmeraldElectricFurnace:
    customModelID: 12
  IronFoundry:
    customModelID: 15
  IronElectricFoundry:
    customModelID: 5
  GoldElectricFoundry:
    customModelID: 6
  DiamondElectricFoundry:
    customModelID: 7
  EmeraldElectricFoundry:
    customModelID: 8
  crystal:
    customModelID: 16
  CopperOre:
    customModelID: 602
  IronMacerator:
    customModelID: 17
  GoldMacerator:
    customModelID: 18
  DiamondMacerator:
    customModelID: 19
  EmeraldMacerator:
    customModelID: 20
  BasicSolarPanel:
    customModelID: 21
  SolarPanel:
    customModelID: 22
  CompactedSolarPanel:
    customModelID: 23
  SolarArray:
    customModelID: 24
  GeothermalGenerator:
    customModelID: 26
  WindGenerator:
    customModelID: 27
  Magnetiser:
    customModelID: 28
  MagnetisingTable:
    customModelID: 29
  sickle_wood:
    customModelID: 1
  sickle_stone:
    customModelID: 2
  sickle_iron:
    customModelID: 3
  sickle_steel:
    customModelID: 4
  sickle_copper:
    customModelID: 5
  sickle_gold:
    customModelID: 6
  sickle_diamond:
    customModelID: 7
  engineers_hammer:
    customModelID: 8

  lava_0_b:
    customModelID: 70
  lava_1_b:
    customModelID: 71
  lava_2_b:
    customModelID: 72
  lava_3_b:
    customModelID: 73
  lava_4_b:
    customModelID: 74
  lava_5_b:
    customModelID: 75
  lava_6_b:
    customModelID: 76
  lava_7_b:
    customModelID: 77
  lava_8_b:
    customModelID: 78
  lava_9_b:
    customModelID: 79
  lava_10_b:
    customModelID: 80
  lava_11_b:
    customModelID: 81
  lava_12_b:
    customModelID: 82
  lava_13_b:
    customModelID: 83
  lava_14_b:
    customModelID: 84
  lava_15_b:
    customModelID: 85
  lava_16_b:
    customModelID: 86
  lava_17_b:
    customModelID: 87
  lava_18_b:
    customModelID: 88
  lava_19_b:
    customModelID: 89
  lava_20_b:
    customModelID: 90
  lava_0_t:
    customModelID: 91
  lava_1_t:
    customModelID: 92
  lava_2_t:
    customModelID: 93
  lava_3_t:
    customModelID: 94
  lava_4_t:
    customModelID: 95
  lava_5_t:
    customModelID: 96
  lava_6_t:
    customModelID: 97
  lava_7_t:
    customModelID: 98
  lava_8_t:
    customModelID: 99
  lava_9_t:
    customModelID: 100
  lava_10_t:
    customModelID: 101
  lava_11_t:
    customModelID: 102
  lava_12_t:
    customModelID: 103
  lava_13_t:
    customModelID: 104
  lava_14_t:
    customModelID: 105
  lava_15_t:
    customModelID: 106
  lava_16_t:
    customModelID: 107
  lava_17_t:
    customModelID: 108
  lava_18_t:
    customModelID: 109
  lava_19_t:
    customModelID: 110
  lava_20_t:
    customModelID: 111
  windmill:
    customModelID: 128
  waterwheel:
    customModelID: 131
  upgrade_card_iron:
    customModelID: 1
  upgrade_card_gold:
    customModelID: 1
  upgrade_card_diamond:
    customModelID: 1
  upgrade_card_emerald:
    customModelID: 1
  BlockBreaker:
    customModelID: 31
  BlockBreaker_SOUTH:
    customModelID: 33
  BlockBreaker_WEST:
    customModelID: 34
  BlockBreaker_EAST:
    customModelID: 32
  BlockPlacer:
    customModelID: 35
  BlockPlacer_SOUTH:
    customModelID: 37
  BlockPlacer_WEST:
    customModelID: 38
  BlockPlacer_EAST:
    customModelID: 36