items:
  iron_core:
    customModelID: 1001
  gold_core:
    customModelID: 1001
  diamond_core:
    customModelID: 1001
  emerald_core:
    customModelID: 1001
  magnetised_iron:
    customModelID: 1001
  copper_ingot:
    customModelID: 1001
  wrench:
    customModelID: 10061
  configurator:
    customModelID: 10062
  steel_ingot:
    customModelID: 1001
  steel_dust:
    customModelID: 1001
  iron_dust:
    customModelID: 1001
  gold_dust:
    customModelID: 1001
  diamond_dust:
    customModelID: 1001
  emerald_dust:
    customModelID: 1001
  copper_dust:
    customModelID: 1001
  coal_dust:
    customModelID: 1001

  light_off:
    customModelID: 10063
  light_on:
    customModelID: 10065
  invisible:
    customModelID: 1005
  output:
    customModelID: 1006
  output_disabled:
    customModelID: 1007
  output_green:
    customModelID: 1008
  output_disabled_alt:
    customModelID: 10067
  output_green_alt:
    customModelID: 10068
  bar_0_b:
    customModelID: 1009
  bar_1_b:
    customModelID: 10010
  bar_2_b:
    customModelID: 10011
  bar_3_b:
    customModelID: 10012
  bar_4_b:
    customModelID: 10013
  bar_5_b:
    customModelID: 10014
  bar_6_b:
    customModelID: 10015
  bar_7_b:
    customModelID: 10016
  bar_8_b:
    customModelID: 10017
  bar_9_b:
    customModelID: 10018
  bar_10_b:
    customModelID: 10019
  bar_11_b:
    customModelID: 10020
  bar_12_b:
    customModelID: 10021
  bar_13_b:
    customModelID: 10022
  bar_14_b:
    customModelID: 10023
  bar_15_b:
    customModelID: 10024
  bar_16_b:
    customModelID: 10025
  bar_17_b:
    customModelID: 10026
  bar_18_b:
    customModelID: 10027
  bar_19_b:
    customModelID: 10028
  bar_20_b:
    customModelID: 10029
  bar_0_t:
    customModelID: 10030
  bar_1_t:
    customModelID: 10031
  bar_2_t:
    customModelID: 10032
  bar_3_t:
    customModelID: 10033
  bar_4_t:
    customModelID: 10034
  bar_5_t:
    customModelID: 10035
  bar_6_t:
    customModelID: 10036
  bar_7_t:
    customModelID: 10037
  bar_8_t:
    customModelID: 10038
  bar_9_t:
    customModelID: 10039
  bar_10_t:
    customModelID: 10040
  bar_11_t:
    customModelID: 10041
  bar_12_t:
    customModelID: 10042
  bar_13_t:
    customModelID: 10043
  bar_14_t:
    customModelID: 10044
  bar_15_t:
    customModelID: 10045
  bar_16_t:
    customModelID: 10046
  bar_17_t:
    customModelID: 10047
  bar_18_t:
    customModelID: 10048
  bar_19_t:
    customModelID: 10049
  bar_20_t:
    customModelID: 10050
  arrow_0:
    customModelID: 10051
  arrow_1:
    customModelID: 10052
  arrow_2:
    customModelID: 10053
  arrow_3:
    customModelID: 10054
  arrow_4:
    customModelID: 10055
  arrow_5:
    customModelID: 10056
  arrow_6:
    customModelID: 10057
  arrow_7:
    customModelID: 10058
  arrow_8:
    customModelID: 10059
  arrow_9:
    customModelID: 10060
  IronCell:
    customModelID: 1001
  GoldCell:
    customModelID: 1002
  DiamondCell:
    customModelID: 1003
  EmeraldCell:
    customModelID: 1004
  SolidFuelGenerator:
    customModelID: 10013
  power_connector:
    customModelID: 10014
  IronElectricFurnace:
    customModelID: 1009
  GoldElectricFurnace:
    customModelID: 10010
  DiamondElectricFurnace:
    customModelID: 10011
  EmeraldElectricFurnace:
    customModelID: 10012
  IronFoundry:
    customModelID: 10015
  IronElectricFoundry:
    customModelID: 1005
  GoldElectricFoundry:
    customModelID: 1006
  DiamondElectricFoundry:
    customModelID: 1007
  EmeraldElectricFoundry:
    customModelID: 1008
  crystal:
    customModelID: 10016
  CopperOre:
    customModelID: 100602
  IronMacerator:
    customModelID: 10017
  GoldMacerator:
    customModelID: 10018
  DiamondMacerator:
    customModelID: 10019
  EmeraldMacerator:
    customModelID: 10020
  BasicSolarPanel:
    customModelID: 1001
  SolarPanel:
    customModelID: 1001
  CompactedSolarPanel:
    customModelID: 1001
  SolarArray:
    customModelID: 10024
  GeothermalGenerator:
    customModelID: 10026
  RotaryGenerator:
    customModelID: 10027
  Magnetiser:
    customModelID: 10028
  MagnetisingTable:
    customModelID: 10029
  sickle_wood:
    customModelID: 1001
  sickle_stone:
    customModelID: 1002
  sickle_iron:
    customModelID: 1003
  sickle_steel:
    customModelID: 1004
  sickle_copper:
    customModelID: 1005
  sickle_gold:
    customModelID: 1006
  sickle_diamond:
    customModelID: 1007
  engineers_hammer:
    customModelID: 1008

  lava_0_b:
    customModelID: 10070
  lava_1_b:
    customModelID: 10071
  lava_2_b:
    customModelID: 10072
  lava_3_b:
    customModelID: 10073
  lava_4_b:
    customModelID: 10074
  lava_5_b:
    customModelID: 10075
  lava_6_b:
    customModelID: 10076
  lava_7_b:
    customModelID: 10077
  lava_8_b:
    customModelID: 10078
  lava_9_b:
    customModelID: 10079
  lava_10_b:
    customModelID: 10080
  lava_11_b:
    customModelID: 10081
  lava_12_b:
    customModelID: 10082
  lava_13_b:
    customModelID: 10083
  lava_14_b:
    customModelID: 10084
  lava_15_b:
    customModelID: 10085
  lava_16_b:
    customModelID: 10086
  lava_17_b:
    customModelID: 10087
  lava_18_b:
    customModelID: 10088
  lava_19_b:
    customModelID: 10089
  lava_20_b:
    customModelID: 10090
  lava_0_t:
    customModelID: 10091
  lava_1_t:
    customModelID: 10092
  lava_2_t:
    customModelID: 10093
  lava_3_t:
    customModelID: 10094
  lava_4_t:
    customModelID: 10095
  lava_5_t:
    customModelID: 10096
  lava_6_t:
    customModelID: 10097
  lava_7_t:
    customModelID: 10098
  lava_8_t:
    customModelID: 10099
  lava_9_t:
    customModelID: 100100
  lava_10_t:
    customModelID: 100101
  lava_11_t:
    customModelID: 100102
  lava_12_t:
    customModelID: 100103
  lava_13_t:
    customModelID: 100104
  lava_14_t:
    customModelID: 100105
  lava_15_t:
    customModelID: 100106
  lava_16_t:
    customModelID: 100107
  lava_17_t:
    customModelID: 100108
  lava_18_t:
    customModelID: 100109
  lava_19_t:
    customModelID: 100110
  lava_20_t:
    customModelID: 100111
  windmill:
    customModelID: 100128
  waterwheel:
    customModelID: 100131
  upgrade_card_iron:
    customModelID: 1001
  upgrade_card_gold:
    customModelID: 1001
  upgrade_card_diamond:
    customModelID: 1001
  upgrade_card_emerald:
    customModelID: 1001
  BlockBreaker:
    customModelID: 10031
  BlockBreaker_SOUTH:
    customModelID: 10033
  BlockBreaker_WEST:
    customModelID: 10034
  BlockBreaker_EAST:
    customModelID: 10032
  BlockPlacer:
    customModelID: 10035
  BlockPlacer_SOUTH:
    customModelID: 10037
  BlockPlacer_WEST:
    customModelID: 10038
  BlockPlacer_EAST:
    customModelID: 10036