# This is a basic workflow to help you get started with Actions

name: Zip Resource Packs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zip: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Resource Pack
        run: zip -r $GITHUB_WORKSPACE/resourcepacks/original.zip $GITHUB_WORKSPACE/resourcepacks/original
      - name: Zip Resource Pack with Pipes
        run: zip -r $GITHUB_WORKSPACE/resourcepacks/pipes.zip $GITHUB_WORKSPACE/resourcepacks/pipes
      - name: test
        run: ls
      - name: Commit Resource Pack Zip
        run: |
          git config --global user.name 'Craftory Bot'
          git config --global user.email 'craftorybot@users.noreply.github.com'
          git commit -am "chore(resourcepack): update resource pack zips"
          git push
