name: sentryRelease

on:
  push:
    tags:
      - v*

jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1.0.2
        env:
          SENTRY_AUTH_TOKEN: 6a4bcd895f8f4f84b3b58e559061042295c141951d8842a1827013733a46c500
          SENTRY_ORG: craftory
          SENTRY_PROJECT: craftory
        with:
          release: ${{ github.event.release.tag_name }}

